name: Upload Images to Cloudinary

on:
  push:
    branches:
      - main            # la rama principal de tu repo
    paths:
      - "cloudinary/**" # cada vez que subas imágenes aquí, se disparará

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Cloudinary CLI
        run: npm install -g cloudinary-cli

      - name: Upload images to Cloudinary
        run: |
          cloudinary upload cloudinary/ --recursive
        env:
          CLOUDINARY_URL: cloudinary://637177732348531:ItYtyZQUOuk0EMvjTEkQJu_4_3I@dubv2ke0u
